name = "icpump_token_cleanup"
main = "src/lib.rs"
compatibility_date = "2024-01-01"

[vars]
FIREBASE_PROJECT_ID = "project-id"

[build]
command = "cargo install -q worker-build && worker-build --release"