name = "storj-bulk-upload"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
# TODO: Move this build command to build.sh, which distinguishes between local and prod builds
command = "cargo install -q worker-build && worker-build --release --features 'storj-bulk-upload/local'"

[vars]
ENVIRONMENT = "production"
# the filter timestamp must be set from the dashboard
# all posts under this timestamp will be duplicated (non-inclusively)
# must be RFC3339
# must be UTC
# example value:
# LOW_PASS_TIMESTAMP = "2024-12-31T00:00:00Z"

[[d1_databases]]
binding = "STORJ_STAGING_DB"
database_name = "STORJ_STAGING_DB"
database_id = "b1490f77-c608-49d8-89cc-7b73703df6b5"

[env.development.vars]
ENVIRONMENT = "development"
LOW_PASS_TIMESTAMP = "2024-12-31T00:00:00Z" 

[[env.development.d1_databases]]
binding = "STORJ_STAGING_DB"
database_name = "STORJ_STAGING_DB"
database_id = "b1490f77-c608-49d8-89cc-7b73703df6b5"

