# TODO: change this back to prod name
name = "hon-test-yral-pump-n-dump"
main = "build/worker/shim.mjs"
compatibility_date = "2024-12-22"

[durable_objects]
bindings = [
  { name = "USER_EPHEMERAL_STATE", class_name = "UserEphemeralState" },
  { name = "GAME_STATE", class_name = "GameState" },
]

[[migrations]]
tag = "v0.1"
new_classes = ["UserEphemeralState", "GameState"]

[build]
command = "cargo install -q worker-build && worker-build --profiling"


tail_consumers = [{ service = "tail-worker-yral" }]
