name = "yral-hot-or-not-test"
main = "build/worker/shim.mjs"
compatibility_date = "2025-05-04"
tail_consumers = [{ service = "tail-worker-yral" }]


[durable_objects]
bindings = [{ name = "USER_HON_GAME_STATE", class_name = "UserHonGameState" }]

[[migrations]]
tag = "v0.1"
new_classes = ["UserHonGameState"]

[build]
command = "cargo install worker-build --version 0.1.4 --force && worker-build --release"
# revert back once https://github.com/cloudflare/workers-rs/issues/808 is fixed
