[package]
name = "yral-worker-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
worker.workspace = true
serde.workspace = true
serde_bytes.workspace = true
rmp-serde.workspace = true
serde-wasm-bindgen.workspace = true
candid.workspace = true
serde_json.workspace = true