name: Lint and Test

on:
  pull_request:
    branches:
      - '**'

  workflow_call:
    inputs:
      working-directory:
        description: 'Directory to run cargo checks'
        required: false
        default: '.'
        type: string

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    env:
      WORKING_DIRECTORY: ${{ github.event.inputs.working-directory || '.' }}

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - uses: actions/checkout@v4

      - name: Validate working directory
        run: |
          if [ ! -d "${WORKING_DIRECTORY}" ]; then
            echo "Error: Working directory '${WORKING_DIRECTORY}' does not exist."
            exit 1
          fi

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy,rustfmt
      
      - name: Install protoc
        run: |
          sudo apt-get install protobuf-compiler

      - uses: Swatinem/rust-cache@v2

      - name: Lint check
        run: |
          cargo fmt --check
          cargo clippy --workspace --all-targets --no-deps -- -D warnings

      - name: Run Tests
        run: cargo test --workspace --all-targets --all-features --jobs 4
