name: Deploy KV fetch worker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "workers/kv-fetch/**"
      - ".github/workflows/deploy-kv-fetch.yml"

jobs:
  deploy-worker:
    name: Deploy kv-fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_FULL_EDIT_ACCESS_INCLUDING_BINDINGS }}
          workingDirectory: workers/kv-fetch
